#!/usr/bin/env bash

toggle_location() {
	location_list=("Christchurch" "Queenstown" "Wellington" "Auckland")
	STATE_FILE="$HOME/.config/sway/waybar/weather_location_cycle"

	if [[ -f "$STATE_FILE" ]]; then
		index=$(cat "$STATE_FILE")
	else
		index=0
	fi
	curl -s 'wttr.in/'"${location_list[$index]}"'/?format=4'
	index=$(( (index + 1) % ${#location_list[@]} ))
	echo "$index" > "$STATE_FILE"
}

hover() {
	location_list=("Christchurch" "Queenstown" "Wellington" "Auckland")

	for i in "${location_list[@]}"
	do
		curl -s 'wttr.in/'{"$i","$i","$i","$i"}'/?format=4'
	done
}

if [[ "$1" == '--toggle' ]]; then
	toggle_location
else
	curl -s 'wttr.in/Christchurch/?format=4'
fi
